/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skype;

import java.awt.CardLayout;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static skype.Login.result1;
import static skype.Login.skypeid;

/**
 *
 * @author listeruser
 */
public class Home extends javax.swing.JFrame implements Runnable {

    private static final long serialVersionUID = 1L;
    BufferedReader inputLine;
    boolean closed = false;
    static PrintStream out;
    static DataInputStream in;
    Thread t2=null;
    Thread t3 = null;
    static int c = 0;
    ListModel m = null;
        
    String fname;
    String lname;
    String email;
    String picurl;
    String status;
    String mood;
    String grouplist;
    String contactlist;
    String recid;
    String fullname;
    boolean isGroup = false;
   
    DefaultListModel<String> df=new  DefaultListModel<String>();

    String username = "Set User Name";
    public String responseLine = "";

    public Home(PrintStream out, DataInputStream in) {
        this.out = out;
        this.in = in;
        initComponents();
        String details[] = result1.split("\\s+");
  
        fname = details[0];
        lname = details[1];
        email = details[2];
        picurl = details[3];
        status = details[4];
        mood = details[5];
        grouplist = details[6];
        
        contactlist=details[7];
       
        String cons[]=contactlist.split("\\$");
        df.removeAllElements();
        for(int i=0;i<cons.length;i++){
            
            cons[i]=cons[i].replaceAll("\\*", " ");
            df.addElement(cons[i]);
            ContactList1.setModel(df);
        }
        
        

        String groups[] = grouplist.split(":");
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+skypeid+".jpg")));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+skypeid+".png")));
        

        jButton11.setText(fname + " " + lname);
        jLabel7.setText(fname + " " + lname);
        jLabel17.setText(skypeid);
        jLabel18.setText(email);
    }

    public Home(PrintStream out, DataInputStream in, JTextArea jx) {
        this.out = out;
        this.in = in;
        initComponents();
        String details[] = result1.split("\\s+");
        fname = details[0];
        lname = details[1];
        email = details[2];
        picurl = details[3];
        status = details[4];
        mood = details[5];
        grouplist = details[6];

        String groups[] = grouplist.split(":");

        jButton11.setText(fname + " " + lname);
        jLabel7.setText(fname + " " + lname);
        jLabel17.setText(skypeid);
        jLabel18.setText(email);
        jTextArea1 = jx;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        CardPanel = new javax.swing.JPanel();
        HomeCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ProfileCard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ConversationCard = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AddGroup = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        SidePanel1 = new javax.swing.JPanel();
        searchIcon1 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        PeoplePanel = new javax.swing.JPanel();
        Contacts1 = new javax.swing.JScrollPane();
        ContactList1 = new javax.swing.JList();
        Groups = new javax.swing.JScrollPane();
        ContactList2 = new javax.swing.JList();
        jButton12 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Background1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(106, 173, 226));
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPanel.setBackground(new java.awt.Color(251, 252, 254));
        MainPanel.setPreferredSize(new java.awt.Dimension(860, 540));

        CardPanel.setLayout(new java.awt.CardLayout());

        HomeCard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Find your friends and say hello ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Look for Skype++ contacts in your address book, then send an");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("instant message or make a video call - just to say hi! ");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_bottom.png"))); // NOI18N

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 240, 246)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setText("What's on your mind?");

        javax.swing.GroupLayout HomeCardLayout = new javax.swing.GroupLayout(HomeCard);
        HomeCard.setLayout(HomeCardLayout);
        HomeCardLayout.setHorizontalGroup(
            HomeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
            .addGroup(HomeCardLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(HomeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeCardLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeCardLayout.createSequentialGroup()
                        .addGroup(HomeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeCardLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(130, 130, 130)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeCardLayout.setVerticalGroup(
            HomeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeCardLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15))
        );

        CardPanel.add(HomeCard, "HomeCard");

        ProfileCard.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar_default.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 120));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 120));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 120));
        jLabel5.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Change picture");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Public", "Contacts only", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel7.setText("Pranathi Mylavarapu");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jLabel8.setText("Email id");

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jLabel9.setText("Status");

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jLabel10.setText("Skype name");

        javax.swing.GroupLayout ProfileCardLayout = new javax.swing.GroupLayout(ProfileCard);
        ProfileCard.setLayout(ProfileCardLayout);
        ProfileCardLayout.setHorizontalGroup(
            ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileCardLayout.createSequentialGroup()
                .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileCardLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfileCardLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileCardLayout.createSequentialGroup()
                        .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(59, 59, 59)
                        .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)))
                    .addGroup(ProfileCardLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel7)))
                .addGap(90, 90, 90))
        );
        ProfileCardLayout.setVerticalGroup(
            ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileCardLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileCardLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileCardLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(ProfileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel19))
                        .addGap(82, 82, 82)
                        .addComponent(jLabel20)))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        CardPanel.add(ProfileCard, "ProfileCard");

        ConversationCard.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/videoIcon.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/end.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 253)));
        jScrollPane1.setViewportView(jTextArea1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attach.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jLabel11.setText("Pranathi Mylavarapu");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Round Profile Pic.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("online");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_tiny.png"))); // NOI18N

        javax.swing.GroupLayout ConversationCardLayout = new javax.swing.GroupLayout(ConversationCard);
        ConversationCard.setLayout(ConversationCardLayout);
        ConversationCardLayout.setHorizontalGroup(
            ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConversationCardLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConversationCardLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ConversationCardLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2)))
                        .addGap(224, 224, 224)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ConversationCardLayout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        ConversationCardLayout.setVerticalGroup(
            ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConversationCardLayout.createSequentialGroup()
                .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConversationCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ConversationCardLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel16)))
                    .addGroup(ConversationCardLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ConversationCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        CardPanel.add(ConversationCard, "ConvoCard");

        AddGroup.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Add your friends to a Group");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_bottom.png"))); // NOI18N

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField3.setToolTipText("");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 240, 246)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel26.setText("Set Group Name");

        jCheckBox1.setText("Aravind Vaideesh");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Arnab Mondal");

        jCheckBox3.setText("Arun Prasanna");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Ayush Kumarsinha");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Kirthika R");

        jCheckBox10.setText("Laavanya WLN");

        jCheckBox11.setText("Nandita Sudalagunta");

        jCheckBox12.setText("Pranathi Mylavarapu");

        jCheckBox5.setText("Preethi S");

        jCheckBox6.setText("Sahithi Palakurthi");

        jCheckBox7.setText("Saikrishna S");

        jCheckBox8.setText("Sakthi Priya");
        jCheckBox8.setToolTipText("");

        jCheckBox13.setText("Sirisha Cherala");

        jCheckBox14.setText("Sravana Jyothi");

        jCheckBox15.setText("Sushmethaa Muhundan");

        jCheckBox16.setText("Vijaya Nandhini");

        jButton6.setText("Create Group");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddGroupLayout = new javax.swing.GroupLayout(AddGroup);
        AddGroup.setLayout(AddGroupLayout);
        AddGroupLayout.setHorizontalGroup(
            AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGroupLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddGroupLayout.createSequentialGroup()
                        .addGroup(AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddGroupLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(134, 134, 134))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddGroupLayout.createSequentialGroup()
                                .addGroup(AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox11)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(150, 150, 150)
                                .addGroup(AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox13)
                                    .addComponent(jCheckBox14)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddGroupLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddGroupLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(191, 191, 191)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddGroupLayout.setVerticalGroup(
            AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddGroupLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddGroupLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addGap(4, 4, 4)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox12))
                    .addGroup(AddGroupLayout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8)
                        .addGap(4, 4, 4)
                        .addComponent(jCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24))
        );

        CardPanel.add(AddGroup, "AddGroup");

        SidePanel1.setBackground(new java.awt.Color(245, 252, 254));
        SidePanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        SidePanel1.setLayout(null);

        searchIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchBlue.png"))); // NOI18N
        searchIcon1.setToolTipText("");
        SidePanel1.add(searchIcon1);
        searchIcon1.setBounds(10, 130, 20, 20);

        search1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        search1.setForeground(java.awt.Color.gray);
        search1.setText("search");
        search1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        search1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search1FocusLost(evt);
            }
        });
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        SidePanel1.add(search1);
        search1.setBounds(40, 130, 170, 27);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        SidePanel1.add(jButton9);
        jButton9.setBounds(10, 90, 70, 30);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Round Profile Pic.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.setFocusPainted(false);
        jButton10.setHideActionText(true);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        SidePanel1.add(jButton10);
        jButton10.setBounds(10, 30, 60, 50);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jButton11.setText("Pranathi Mylavarapu");
        jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.setMaximumSize(null);
        jButton11.setMinimumSize(null);
        jButton11.setPreferredSize(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        SidePanel1.add(jButton11);
        jButton11.setBounds(70, 40, 160, 20);

        PeoplePanel.setLayout(new java.awt.CardLayout());

        Contacts1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Contacts1MouseClicked(evt);
            }
        });

        ContactList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        ContactList1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ContactList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Aravind Vaideesh", "Arnab Mondal", "Arun Prasanna", "Ayush Kumarsinha", "Kirthika R", "Laavanya WLN", "Nandita Sudalagunta", "Pranathi Mylavarapu", "Preethi S", "Sahithi Palakurthi", "Saikrishna S", "Sakthi Priya", "Sirisha Cherala", "Sravana Jyothi", "Sushmethaa Muhundan", "Vijaya Nandhini" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ContactList1.setName("contactList"); // NOI18N
        ContactList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactList1MouseClicked(evt);
            }
        });
        ContactList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ContactList1ValueChanged(evt);
            }
        });
        Contacts1.setViewportView(ContactList1);

        PeoplePanel.add(Contacts1, "PeopleCard");

        ContactList2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        ContactList2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ContactList2.setName("contactList"); // NOI18N
        ContactList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactList2MouseClicked(evt);
            }
        });
        ContactList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ContactList2ValueChanged(evt);
            }
        });
        Groups.setViewportView(ContactList2);

        PeoplePanel.add(Groups, "GroupCard");

        SidePanel1.add(PeoplePanel);
        PeoplePanel.setBounds(10, 200, 220, 260);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Groups");
        jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton12.setBorderPainted(false);
        jButton12.setFocusPainted(false);
        jButton12.setFocusable(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.setRolloverEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        SidePanel1.add(jButton12);
        jButton12.setBounds(110, 160, 100, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("People");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        SidePanel1.add(jButton3);
        jButton3.setBounds(10, 160, 90, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createGrp.png"))); // NOI18N
        jButton7.setToolTipText("");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        SidePanel1.add(jButton7);
        jButton7.setBounds(190, 80, 30, 40);

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sideBack.png"))); // NOI18N
        SidePanel1.add(Background1);
        Background1.setBounds(0, 0, 230, 523);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addComponent(SidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 701, Short.MAX_VALUE)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addComponent(SidePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(MainPanel, "card2");

        jMenuBar1.setBackground(new java.awt.Color(201, 222, 251));
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));

        jMenu1.setBackground(new java.awt.Color(56, 166, 241));
        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setForeground(java.awt.Color.darkGray);
        jMenu1.setText("Skype++");
        jMenu1.setAutoscrolls(true);
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jMenu1.setRequestFocusEnabled(false);

        jMenuItem10.setText("Profile");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem2.setText("Privacy");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Sign out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(138, 200, 233));
        jMenu2.setForeground(java.awt.Color.darkGray);
        jMenu2.setText("Contacts");
        jMenu2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N

        jMenuItem5.setText("Groups");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Block");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(228, 193, 55));
        jMenu4.setForeground(java.awt.Color.darkGray);
        jMenu4.setText("Help");
        jMenu4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:        
        new Settings1().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           
            
            out.println("videochat "+recid);
            Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "cvlc v4l2:///dev/video0 :v4l2-standard= :input-slave=alsa://hw:0,0 :live-caching=300 --sout '#transcode{vcodec=x264{keyint=60,idrint=2},vcodec=h264,vb=400,width=368,heigh=208,acodec=mpga,ab=32 ,channels=2,samplerate=44100}:duplicate{dst=std{access=http{mime=video/x-ms-wmv},mux=asf,dst=:8082/stream.wmv}}'"});
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

        String msg = jTextField2.getText();

       
        if (isGroup) {
            out.println("groupchat " + fullname);
           
        }
        out.println(msg);
        
        jTextArea1.append("\n" + skypeid + ": " + msg);

        jTextField2.setText("");

        jTextField2.requestFocusInWindow();

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        FileInputStream fis = null;
        try {
            MediaTest mt = new MediaTest();
            URL url = mt.getUrl();
            Transfer t = new Transfer();
            String path = url.toString();
            String FILE_TO_SEND = path.substring(5, path.length());
            File myFile = new File(FILE_TO_SEND);
            
            out.println("file share");
            byte[] mybytearray = new byte[(int) myFile.length()];
            out.println(FILE_TO_SEND);
            
            fis = new FileInputStream(myFile);
            BufferedInputStream bis = new BufferedInputStream(fis);
            try {
                bis.read(mybytearray, 0, mybytearray.length);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (fis != null) {
                try {
                    fis.close();
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    bis.close();
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            jTextArea1.append("\nSending " + FILE_TO_SEND + "(" + mybytearray.length + "bytes)");
            out.write(mybytearray, 0, mybytearray.length);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
        CardLayout card = (CardLayout) CardPanel.getLayout();
        card.show(CardPanel, "ProfileCard");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String status = jTextField1.getText();

        jLabel19.setText(status);
        CardLayout card = (CardLayout) CardPanel.getLayout();
        card.show(CardPanel, "ProfileCard");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            // TODO add your handling code here:
            MediaTest mt=new MediaTest();
            URL url = mt.getUrl();
           
            String path = url.toString();
            
            out.println(skypeid +" "+path+" "+status+" "+mood+" "+"5fff2C");
            String res = in.readLine();
            
            
            if(res.contains("Success")){             
        
                jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+skypeid+".png")));
                
                        
            }
           
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel4MouseEntered

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void search1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search1FocusGained
        
        search1.setText("");
    }//GEN-LAST:event_search1FocusGained

    private void search1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search1FocusLost
       
         search1.setText("search");
    }//GEN-LAST:event_search1FocusLost

    private void search1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_search1KeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) CardPanel.getLayout();
        card.show(CardPanel, "HomeCard");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         CardLayout card = (CardLayout) CardPanel.getLayout();
        card.show(CardPanel, "ProfileCard");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         CardLayout card = (CardLayout) CardPanel.getLayout();
        card.show(CardPanel, "ProfileCard");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void ContactList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactList1MouseClicked
        // TODO add your handling code here:

        try {
            
            if(t2 != null)
                if(t2.isAlive())
                 t2.suspend();
            if(t3 != null)
              if(t3.isAlive())
                t3.suspend();
            // TODO add your handling code here:
            isGroup = false;
            CardLayout card = (CardLayout) CardPanel.getLayout();
            card.show(CardPanel, "ConvoCard");
            int i = ContactList1.getSelectedIndex();
            fullname = (ContactList1.getModel().getElementAt(i)).toString();
            jLabel11.setText(fullname);
            
            
            String[] fname = new String[2];
            fname = fullname.split("\\s+");
            
            out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
            String comb=in.readLine();
            String[] co=comb.split("\\s+");
            recid=co[0];
            String ol=co[1];
            
            jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+recid+".png")));
            if(ol.equals("offline")){
                 jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/of.gif")));
                 jLabel2.setText("offline");
            }
             if(ol.equals("online")){
                 jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_tiny.png")));
                 jLabel2.setText("online");
            }

            out.println(skypeid + " " + recid + " " + "Cfff2C");
            String convo = in.readLine();
            String cnv = convo.replace("$$", "\n");

            

            jTextArea1.setText(cnv);

            //start conversation
            out.println(skypeid + " " + recid + " 6fff2C");
            if (out != null && in != null) {
                
                t3 = new Thread(new Home(out, in, this.jTextArea1));
                t3.start();
            }

          
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ContactList1MouseClicked

    private void ContactList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ContactList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactList1ValueChanged

    private void ContactList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactList2MouseClicked
        try {
            
            if(t3 != null)
             if(t3.isAlive()) {
                
                t3.suspend();
            }
            if(t2 != null)
             if(t2.isAlive()) {
               
                t2.suspend();
            }
            CardLayout card = (CardLayout) CardPanel.getLayout();
            card.show(CardPanel, "ConvoCard");
            int i = ContactList2.getSelectedIndex();
            fullname = (ContactList2.getModel().getElementAt(i)).toString();
            jLabel11.setText(fullname);
            

            isGroup = true;
            out.println(fullname + " " + "Bfff2C");
            String convo = in.readLine();
            String cnv = convo.replace("$$", "\n");
            
            jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
            jTextArea1.setText(cnv);
            jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            jLabel2.setText("");
            out.println(skypeid + " " + fullname + " 6fff2C");
            

            if (out != null && in != null) {
                 t2 = new Thread(new Home(out, in, this.jTextArea1));
                t2.start();

            }

            
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ContactList2MouseClicked

    private void ContactList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ContactList2ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactList2ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         if(t2 != null)
                if(t2.isAlive())
                 t2.suspend();
            if(t3 != null)
              if(t3.isAlive())
                t3.suspend();
        CardLayout card = (CardLayout) PeoplePanel.getLayout();
        card.show(PeoplePanel, "PeopleCard");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Contacts1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Contacts1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Contacts1MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(t3 != null)
            if(t3.isAlive()) {
                System.out.println("alive here");
                t3.suspend();
            }
        try {                                          
            
            // TODO add your handling code here:
            CardLayout card = (CardLayout) PeoplePanel.getLayout();
            card.show(PeoplePanel, "GroupCard");
            out.println(skypeid+" "+"Dfff2C");
            
           
            final String r = in.readLine();
            System.out.println("r="+r);
            if(r.equals("No groups for this user")){
                    
                ContactList2.setModel(new javax.swing.AbstractListModel() {
             
                String[] strings = r.split("\\s+");
                @Override
                public int getSize() { return 0; }
                
                @Override
                public Object getElementAt(int i ) { return null; }
            });
                }
            
            
            else{
                
            ContactList2.setModel(new javax.swing.AbstractListModel() {
              
                
                String[] strings = r.split("\\s+");
                @Override
                public int getSize() { return strings.length; }
                
                @Override
                public Object getElementAt(int i ) { return strings[i]; }
            });
            
            }  
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) CardPanel.getLayout();
        card.show(CardPanel, "AddGroup");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "killall vlc"});
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        List<String> grpnames=new ArrayList<String>();
        
        if(jCheckBox1.isSelected()){
            try {
                String full=jCheckBox1.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox2.isSelected()){
           try {
                String full=jCheckBox2.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox3.isSelected()){
           try {
                String full=jCheckBox3.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox4.isSelected()){
            try {
                String full=jCheckBox4.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox5.isSelected()){
            try {
                String full=jCheckBox5.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox6.isSelected()){
           try {
                String full=jCheckBox6.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox7.isSelected()){
            try {
                String full=jCheckBox7.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox8.isSelected()){
            try {
                String full=jCheckBox8.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox9.isSelected()){
           try {
                String full=jCheckBox9.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox10.isSelected()){
           try {
                String full=jCheckBox10.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
         if(jCheckBox11.isSelected()){
            try {
                String full=jCheckBox11.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox12.isSelected()){
            try {
                String full=jCheckBox12.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox13.isSelected()){
            try {
                String full=jCheckBox13.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox14.isSelected()){
            try {
                String full=jCheckBox14.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox15.isSelected()){
            try {
                String full=jCheckBox15.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(jCheckBox16.isSelected()){
           try {
                String full=jCheckBox16.getText();                
                String[] fname = new String[2];
                fname = full.split("\\s+");
                out.println(fname[0] + " " + fname[1] + " " + "Afff2C");
                String n = in.readLine();
                grpnames.add(n);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        String names="";
        for(int i=0;i<grpnames.size();i++){
            names=names+grpnames.get(i);
            names=names+" ";
        }
        String grp=jTextField3.getText();
       
        out.println(grp+" "+grpnames.size()+" "+names+"9fff2C");
        String res="nothing yet";
        try {
            res = in.readLine();
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        for(int i=0;i<ContactList2.getModel().getSize();i++){
        String s=ContactList2.getModel().getElementAt(i).toString();
        
        df.addElement(s);
        
        }
          
        if(res.contains("Succesfully")){
            df.addElement(grp);
           
             ContactList2.setModel(df);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
         new help_main().setVisible(true);
        
        //new Settings1().setVisible(true);
        
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        new help_main().setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(t3 != null)
            if(t3.isAlive()) {
                System.out.println("alive here");
                t3.suspend();
            }
        try {                                          
            
            // TODO add your handling code here:
            CardLayout card = (CardLayout) PeoplePanel.getLayout();
            card.show(PeoplePanel, "GroupCard");
            out.println(skypeid+" "+"Dfff2C");
            
           
            final String r = in.readLine();
            System.out.println("r="+r);
            if(r.equals("No groups for this user")){
                    
                ContactList2.setModel(new javax.swing.AbstractListModel() {
             
                String[] strings = r.split("\\s+");
                @Override
                public int getSize() { return 0; }
                
                @Override
                public Object getElementAt(int i ) { return null; }
            });
                }
            
            
            else{
                
            ContactList2.setModel(new javax.swing.AbstractListModel() {
              
                
                String[] strings = r.split("\\s+");
                @Override
                public int getSize() { return strings.length; }
                
                @Override
                public Object getElementAt(int i ) { return strings[i]; }
            });
            
            }  
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            if(t3!=null)
                if(t3.isAlive())
                    t3.stop();
            if(t2!=null)
                if(t2.isAlive())
                    t2.stop();
            // TODO add your handling code here:
            out.println(skypeid+" "+"8fff2C");
           
            
            String r=in.readLine();
            
            
            if(r.contains("out")){
                this.dispose();
                Login l=new Login();
                l.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        try {
            // TODO add your handling code here:
            CardLayout card = (CardLayout) CardPanel.getLayout();
            card.show(CardPanel, "ProfileCard");
            out.println(recid+" "+"4fff2C");
            String r=in.readLine();
            String[] details=r.split("\\s+");
            email = details[2];
            picurl = details[3];
            status = details[4];
            mood = details[5];
            jLabel7.setText(fullname);
            jLabel17.setText(skypeid);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+recid+".png")));
        jLabel18.setText(email);
        jLabel19.setText(status);
            
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            CardLayout card = (CardLayout) CardPanel.getLayout();
            card.show(CardPanel, "ProfileCard");
            out.println(recid+" "+"4fff2C");
            String r=in.readLine();
            String[] details=r.split("\\s+");
            email = details[2];
            picurl = details[3];
            status = details[4];
            mood = details[5];
            jLabel7.setText(fullname);
            jLabel17.setText(skypeid);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+recid+".png")));
        jLabel18.setText(email);
        jLabel19.setText(status);
            
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
      
        String[] names = new String[16] ;
          for(int i = 0; i <16 ; i++)
              names[i] = "";
          int size;
          String n = search1.getText();
          if(c==0)
              m =   ContactList1.getModel();
          if(n.equals("")) {
             
               ContactList1.setModel(m);
          }
          else {
              
             size = m.getSize();
          for(int i = 0; i<size;i++) {
    
          names[i] = (String) m.getElementAt(i);
         
          }
          
          ArrayList<String> result = null;
          String[] res = new String[10];
          for(int i=0;i<10;i++)
              res[i] = "";
          String res1 = "";
          int k = 0;
          DefaultListModel model = new DefaultListModel();  
          for(int i=0;i<names.length;i++) 
          {
               if(names[i].startsWith(n)) {
                   res[k] = names[i];
                    model.addElement(res[k]);
                   k++;
               }
               else {}
          }
          for(int i=0;i<k;i++) {
              res1+=res[i];
              res1+="\n";
                      }
          ContactList1.setModel(model);
          }
          c++;
    }//GEN-LAST:event_search1KeyReleased

   
    @Override
    public synchronized  void run() {
        System.out.println("Inside run");

        try {

            while (!closed) {
               
                responseLine = in.readLine();
                
                if(responseLine == null)
                    continue;
                
                if (responseLine.equals("file share")) {
                    
                    String path = in.readLine();
                    
                    Transfer t = new Transfer();
                    
                    t.recv(path, in);
                    
                    in.skipBytes(in.available());   
                   
                } 
                else if(responseLine.contains("TOP")){
                   
                    closed = true;
                   
                }
                else if(responseLine.contains("videosender"))
                       {
                           String[] res = responseLine.split(" ");
                    String my_ip = res[2].substring(1, 13);
                           my_ip+= ":8082";
                    String dest_ip = res[1].substring(1, 13);
                           dest_ip += ":8082";
                           System.out.println("myip - "+my_ip+" dest ip = "+dest_ip);
                           
                               Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "vlc -I dummy --width=100 --height=100 --video-x=100 --video-y=100 --no-video-deco --no-embedded-video http://"+dest_ip+"/stream.wmv"});
                                Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "vlc -I dummy --width=200 --height=200 --video-x=100 --video-y=100 --no-video-deco --no-embedded-video http://"+my_ip+"/stream.wmv"});
          
                       }
                      else if (responseLine.startsWith("videorec")){
                           String ip = null;
                           String[] res = responseLine.split(" ");
                           String my_ip = null;//"10.106.24.16:8082";
                           my_ip = res[2].substring(1,13);
                           my_ip += ":8082";
                           ip = res[1].substring(1, 13);
                           ip += ":8082";
                           System.out.println("my ip = "+my_ip+"\ndest_ip= "+ip);
                           Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "cvlc v4l2:///dev/video0 :v4l2-standard= :input-slave=alsa://hw:0,0 :live-caching=300 --sout '#transcode{vcodec=x264{keyint=60,idrint=2},vcodec=h264,vb=400,width=368,heigh=208,acodec=mpga,ab=32 ,channels=2,samplerate=44100}:duplicate{dst=std{access=http{mime=video/x-ms-wmv},mux=asf,dst=:8082/stream.wmv}}'"});
                           Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "vlc -I dummy --width=100 --height=100 --video-x=100 --video-y=100 --no-video-deco --no-embedded-video http://"+my_ip+"/stream.wmv"});
                           Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", "vlc -I dummy --width=100 --height=100 --video-x=100 --video-y=100 --no-video-deco --no-embedded-video http://"+ip+"/stream.wmv"});
                       
                       }
                else {
                
                    try {
                        String[] s=responseLine.split("\\:");
                        
                        jTextArea1.append("\n"+responseLine);
                        jTextArea1.validate();

                    } catch (Exception e) {
                        System.out.println(e);
                    }

                }

                
            }

            //To change body of generated methods, choose Tools | Templates.
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddGroup;
    private javax.swing.JLabel Background1;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JList ContactList1;
    private javax.swing.JList ContactList2;
    private javax.swing.JScrollPane Contacts1;
    private javax.swing.JPanel ConversationCard;
    private javax.swing.JScrollPane Groups;
    private javax.swing.JPanel HomeCard;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PeoplePanel;
    private javax.swing.JPanel ProfileCard;
    private javax.swing.JPanel SidePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField search1;
    private javax.swing.JLabel searchIcon1;
    // End of variables declaration//GEN-END:variables

}
